
import type { Order } from "./types"

export const mockOrders: Order[] = [
  {
    id: "ORD-2024-001",
    orderDate: "2024-01-15",
    estimatedDelivery: "2024-01-20",
    shippingAddress: {
      street: "123 Main Street, Apt 4B",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "United States",
    },
    deliveryStatus: "Delivered",
    products: [
      {
        id: "prod-1",
        name: "Wireless Bluetooth Headphones",
        description: "Premium noise-cancelling headphones with 30-hour battery life",
        thumbnail: "/placeholder.svg?height=80&width=80",
        quantity: 1,
        price: 199.99,
        totalPrice: 199.99,
      },
      {
        id: "prod-2",
        name: "USB-C Charging Cable",
        description: "Fast charging cable compatible with most devices",
        thumbnail: "/placeholder.svg?height=80&width=80",
        quantity: 2,
        price: 24.99,
        totalPrice: 49.98,
      },
    ],
    paymentMethod: "Credit Card (**** 1234)",
    paymentStatus: "Paid",
    totalAmount: 249.97,
  },
  {
    id: "ORD-2024-002",
    orderDate: "2024-01-18",
    estimatedDelivery: "2024-01-25",
    shippingAddress: {
      street: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
      country: "United States",
    },
    deliveryStatus: "In Transit",
    products: [
      {
        id: "prod-3",
        name: "Smart Watch Series 9",
        description: "Advanced fitness tracking with heart rate monitor",
        thumbnail: "/placeholder.svg?height=80&width=80",
        quantity: 1,
        price: 399.99,
        totalPrice: 399.99,
      },
    ],
    paymentMethod: "PayPal",
    paymentStatus: "Paid",
    totalAmount: 399.99,
  },
  {
    id: "ORD-2024-003",
    orderDate: "2024-01-20",
    estimatedDelivery: "2024-01-27",
    shippingAddress: {
      street: "789 Pine Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
      country: "United States",
    },
    deliveryStatus: "Pending",
    products: [
      {
        id: "prod-4",
        name: "Laptop Stand",
        description: "Adjustable aluminum laptop stand for better ergonomics",
        thumbnail: "/placeholder.svg?height=80&width=80",
        quantity: 1,
        price: 79.99,
        totalPrice: 79.99,
      },
      {
        id: "prod-5",
        name: "Wireless Mouse",
        description: "Ergonomic wireless mouse with precision tracking",
        thumbnail: "/placeholder.svg?height=80&width=80",
        quantity: 1,
        price: 49.99,
        totalPrice: 49.99,
      },
      {
        id: "prod-6",
        name: "Mechanical Keyboard",
        description: "RGB backlit mechanical keyboard with blue switches",
        thumbnail: "/placeholder.svg?height=80&width=80",
        quantity: 1,
        price: 129.99,
        totalPrice: 129.99,
      },
    ],
    paymentMethod: "Credit Card (**** 5678)",
    paymentStatus: "Pending",
    totalAmount: 259.97,
  },
]
